apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend
        image: umer3101/mern-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"

